//Auto-generated by avrCommon.mk

#ifndef __PROJINFO_H__
#define __PROJINFO_H__
#include <inttypes.h>

#if (defined(_PROJINFO_OVERRIDE_) && _PROJINFO_OVERRIDE_)
 const uint8_t __attribute__ ((progmem)) \
   header[] = "";
#elif (defined(PROJINFO_SHORT) && PROJINFO_SHORT)
 const uint8_t __attribute__ ((progmem)) \
   header[] = "anaButtonsTesttestMega328p+NonBlocking 2014-12-30 16:02:06";
#else //projInfo Not Shortened nor overridden
 const uint8_t __attribute__ ((progmem)) \
   header0[] = " /home/meh/_commonCode/anaButtons/0.50-gitHubbing/testMega328p+NonBlocking ";
 const uint8_t __attribute__ ((progmem)) \
   header1[] = " Tue Dec 30 16:02:06 PST 2014 ";
 const uint8_t __attribute__ ((progmem)) \
   headerOpt[] = "  ";
#endif

//For internal use...
//Currently only usable in main.c
#define PROJ_VER testMega328p+NonBlocking
#define COMPILE_YEAR 2014

#endif

